=== Diffalex/Boveda-1DAM/Lenguajes de marcas/Ejercicios/DTD/recetas/recetas_41.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT recetas (receta*)>
<!ELEMENT receta (ingredientes, elaboracion)>
<!ATTLIST receta nombre CDATA #REQUIRED numero_raciones CDATA #REQUIRED dificultad CDATA #REQUIRED>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (nombre, cantidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad unidad CDATA #REQUIRED>
<!ELEMENT elaboracion (paso*)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST paso cod_paso CDATA #REQUIRED>

=== Diffalex/Boveda-1DAM/Lenguajes de marcas/Ejercicios/DTD/recetas/recetas_41.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM "recetas_41.dtd">
<recetas>
    <receta nombre="" numero_raciones="" dificultad="">
        <ingredientes>
            <ingrediente>
                <nombre></nombre>
                <cantidad unidad=""></cantidad>
            </ingrediente>
        </ingredientes>
        <elaboracion>
            <paso cod_paso=""></paso>
        </elaboracion>
    </receta>
    <receta nombre="" numero_raciones="" dificultad="">
        <ingredientes>
            <ingrediente>
                <nombre></nombre>
                <cantidad unidad=""></cantidad>
            </ingrediente>
        </ingredientes>
        <elaboracion>
            <paso cod_paso=""></paso>
        </elaboracion>
    </receta>
    <receta nombre="" numero_raciones="" dificultad="">
        <ingredientes>
            <ingrediente>
                <nombre></nombre>
                <cantidad unidad=""></cantidad>
            </ingrediente>
        </ingredientes>
        <elaboracion>
            <paso cod_paso=""></paso>
        </elaboracion>
    </receta>
</recetas>
