=== Diffalex/Boveda-1DAM/Lenguajes de marcas/Ejercicios/DTD/agenda/agenda.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT agenda (propietario, contactos)>
<!ELEMENT propietario (identificadores, direccion, telefonos)>
<!ELEMENT identificadores (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direccion (calle, localidad, cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT telefonos (movil?, casa?, trabajo?)>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT casa (#PCDATA)>
<!ELEMENT trabajo (#PCDATA)>
<!ELEMENT contactos (persona+)>
<!ELEMENT persona (identificadores, direccion, telefonos)>
<!ATTLIST persona cod_persona CDATA #REQUIRED>

=== Diffalex/Boveda-1DAM/Lenguajes de marcas/Ejercicios/DTD/agenda/agenda_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <propietario>
      <identificadores>
        <nombre>Alma</nombre>
        <apellidos>López Terán</apellidos>
      </identificadores>
      <direccion>
        <calle>El Percebe 13, 6F</calle>
        <localidad>Torrelavega</localidad>
        <cp>39300</cp>
      </direccion>
      <telefonos>
        <movil>970898765</movil>
        <casa>942124567</casa>
        <trabajo>628983456</trabajo>
      </telefonos>
    </propietario>
  <contactos>
      <persona cod_persona="p01">
        <identificadores>
          <nombre>Inés</nombre>
          <apellidos>López Pérez</apellidos>
        </identificadores>
        <direccion>
          <calle>El Ranchito 24, 6B</calle>
          <localidad>Santander</localidad>
          <cp>39006</cp>
        </direccion>
        <telefonos>
          <movil>970123123</movil>
        </telefonos>
      </persona>
      <persona cod_persona="p02">
        <identificadores>
          <nombre>Roberto</nombre>
          <apellidos>Gutiérrez Gómez</apellidos>
        </identificadores>
        <direccion>
          <calle>El Marranito 4, 2F</calle>
          <localidad>Santander</localidad>
          <cp>39004</cp>
        </direccion>
        <telefonos>
          <movil>970987456</movil>
          <casa>942333323</casa>
        </telefonos>
      </persona>
      <persona cod_persona="03">
        <identificadores>
          <nombre>Juan</nombre>
          <apellidos>Sánchez Martínez</apellidos>
        </identificadores>
        <direccion>
          <calle>El Cangrejo 10, sn</calle>
          <localidad>Torrelavega</localidad>
          <cp>39300</cp>
        </direccion>
        <telefonos>
          <movil>997564343</movil>
          <casa>942987974</casa>
          <trabajo>677899234</trabajo>
        </telefonos>
    </persona>
  </contactos>
</agenda>

=== Diffalex/Boveda-1DAM/Lenguajes de marcas/Ejercicios/DTD/agenda/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">

<agenda>
    <propietario>
        <identificadores>
            <nombre></nombre>
            <apellidos></apellidos>
        </identificadores>
        <direccion>
            <calle></calle>
            <localidad></localidad>
          <cp></cp>
        </direccion>
        <telefonos>
            <movil></movil>
            <casa></casa>
            <trabajo></trabajo>
        </telefonos>
    </propietario>
    <contactos>
        <persona cod_persona="">
            <identificadores>
                <nombre></nombre>
                <apellidos></apellidos>
            </identificadores>
            <direccion>
                <calle></calle>
                <localidad></localidad>
                <cp></cp>
            </direccion>
            <telefonos>
                <movil></movil>
                <casa></casa>
                <trabajo></trabajo>
            </telefonos>
        </persona>
    </contactos>
</agenda>
